<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-BIER98A" name="testinguy.appium.main.mainTest2" tests="5" failures="1" timestamp="13 may 2019 13:18:23 GMT" time="22.008" errors="0">
  <testcase name="IniciarSesion" time="6.325" classname="testinguy.appium.main.mainTest2"/>
  <testcase name="testCaseSkipException" time="0.000" classname="testinguy.appium.main.mainTest2">
    <skipped/>
  </testcase> <!-- testCaseSkipException -->
  <testcase name="Test_Slider" time="9.009" classname="testinguy.appium.main.mainTest2"/>
  <testcase name="Test_DragAndDrop" time="6.674" classname="testinguy.appium.main.mainTest2">
    <failure type="java.lang.AssertionError" message="expected [Circle droppedxD] but found [Circle dropped]">
      <![CDATA[java.lang.AssertionError: expected [Circle droppedxD] but found [Circle dropped]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testinguy.appium.main.mainTest2.Test_DragAndDrop(mainTest2.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_DragAndDrop -->
  <testcase name="Test_NativeView" classname="testinguy.appium.main.mainTest2">
    <skipped/>
  </testcase> <!-- Test_NativeView -->
</testsuite> <!-- testinguy.appium.main.mainTest2 -->
